export const EXERCISE_NAMES: Record<string, string> = {
  bb_bench_press: 'Barbell Bench Press',
  db_bench_press: 'Dumbbell Bench Press',
  incline_db_press: 'Incline Dumbbell Press',
  machine_chest_press: 'Machine Chest Press',
  cable_fly: 'Cable Chest Fly',
  push_up: 'Push-Up',
  deadlift: 'Barbell Deadlift',
  pull_up: 'Pull-Up',
  lat_pulldown: 'Lat Pulldown',
  barbell_row: 'Barbell Row',
  db_row: 'Dumbbell Row',
  seated_cable_row: 'Seated Cable Row',
  face_pull: 'Face Pull',
  ohp: 'Overhead Press',
  db_shoulder_press: 'Dumbbell Shoulder Press',
  lateral_raise: 'Lateral Raise',
  rear_delt_fly: 'Rear Delt Fly',
  bb_curl: 'Barbell Curl',
  db_curl: 'Dumbbell Curl',
  hammer_curl: 'Hammer Curl',
  tricep_pushdown: 'Cable Tricep Pushdown',
  overhead_tricep_ext: 'Overhead Tricep Extension',
  close_grip_bench: 'Close-Grip Bench Press',
  back_squat: 'Barbell Back Squat',
  front_squat: 'Barbell Front Squat',
  leg_press: 'Leg Press',
  hack_squat: 'Hack Squat',
  bulgarian_split_squat: 'Bulgarian Split Squat',
  rdl: 'Romanian Deadlift',
  leg_curl: 'Leg Curl',
  hip_thrust: 'Barbell Hip Thrust',
  standing_calf_raise: 'Standing Calf Raise',
  seated_calf_raise: 'Seated Calf Raise',
  plank: 'Plank',
  hanging_leg_raise: 'Hanging Leg Raise',
  cable_crunch: 'Cable Crunch',
};
