version = 0.1

[default.global.parameters]
stack_name = "strength-pilot-dev"

[default.build.parameters]
parallel = true
cached = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
s3_prefix = "strength-pilot"
